version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: Bookmark
    environment:
      POSTGRES_DB: Dhruv-Bookmark
      POSTGRES_USER: Dhruv
      POSTGRES_PASSWORD: Dhruv@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
 
volumes:
  postgres_data:
